### PR TITLE
Add date as property on Match

### LINKED ISSUE #214: Add date as property on Match

### PR DESCRIPTION
**Pull request by Swopper050**
Closes #214

### CODE REVIEW

**Comment by Swopper050** [comment]
@Alek050 Do you know why the codecov patch is failing? I'm not sure how to add coverage to the two lines it says its missing

**Comment by Alek050** [comment]
Hi @Swopper050 

I am not really sure what is happening, Codecov has been working poorly lately but have not seen this before. However, I think you do not have the latest version of develop merged in your branch. In `match.py`, the methods `shots_df`, `passes_df`, and `dribbles_df` are calculated differently on Alek050/databallpy/develop than on your code. Could you try pulling and merging develop in you branch and rerunning the actions after this change?

**Comment by Swopper050** [comment]
@Alek050 I think I branched from main. Should be updated now.

**Comment by Alek050** [comment]
Looks like it fails on some of the lines I updated in an earlier PR, but back then Codecov was not working properly. I'll approve the PR.

**Review by Alek050 — APPROVED** [review]

**Pull request merged**
