### PR TITLE
Install poetry before running make commands that use poetry

### PR DESCRIPTION
**Pull request by Swopper050**
Related issue: #130 

Questions @Alek050 : 
 - Does `databallpy` require a specific poetry version?
 - Is it normal to install poetry in a virtual environment or is this usually installed globally?

### CODE REVIEW

**Comment by Alek050** [comment]
Hi @Swopper050 

Just looked into the documentation of `poetry` and it seems like that they have made it possible to install poetry using `pip`. Not totally sure if this fully works since I had to add and remove some files manually when installing `poetry`, but if it works for you that could indeed make the installation for developers easier as you mentioned in #130. Can you figure out if the pip install is the only thing you have to do when installing poetry for the first time? I think it will not work fully since they still have a individual point 3 "Add poetry to your PATH": https://python-poetry.org/docs/#installation.

Regarding the versioning, I've used versions between 1.3 up and untill 1.6.2 (newest version I think), so for now I would suggest just installing the newest version, I might need to add documentation somewhere on what versions to use, good point.

To be fair, I am not if installing `poetry` globally is recomended behaviour, but for my current use I have it installed globally. I use `poetry` mainly as dependency manager so do not see use for installing it in a virtual environment now, maybe in the future when version 2.0 is released I might need to change this.

Thanks for opening a disucssion on this and hope you will contribute to the project!

**Comment by Swopper050** [comment]
@Alek050 I just created a virtual env (`python3 -m venv .env`), activated it, ran `pip install poetry` and then did `make deps` and all the other commands just worked fine so I guess using `pip install` works? (At least on my machine)

**Comment by Swopper050** [comment]
@Alek050 To be honest, after reading the poetry docs you mentioned, it seems their preferred way of installation is via their installer you can download via curl.

Maybe it is better to stick to their recommended way. The README can then be updated to mention a developer to install poetry first and link to the installation docs.

**Comment by Alek050** [comment]
@Swopper050 

After using the curl download, the `pip install --upgrade poetry` in the deps will not work anymore since `poetry` is not installed using pip right? Can we than close this pull request without merging?

**Comment by Swopper050** [comment]
@Alek050 Yes I will close it, and update the issue

**Pull request closed without merging**
